// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW7tVEoUkSN97f1ls8hIUt1Igqt_LYoCY',
    appId: '1:413507224369:web:8f12bdfeba7344bb032610',
    messagingSenderId: '413507224369',
    projectId: 'instaclone-95fd6',
    authDomain: 'instaclone-95fd6.firebaseapp.com',
    storageBucket: 'instaclone-95fd6.appspot.com',
    measurementId: 'G-03X6K9ZSN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ScdSO71FxoShuEU-ouulLusSUDeBMDA',
    appId: '1:413507224369:android:1598193c0291034f032610',
    messagingSenderId: '413507224369',
    projectId: 'instaclone-95fd6',
    storageBucket: 'instaclone-95fd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASGAJvqDsQ66FMOlTtJJi_SZlUHWEkgx8',
    appId: '1:413507224369:ios:de575ef905676e5d032610',
    messagingSenderId: '413507224369',
    projectId: 'instaclone-95fd6',
    storageBucket: 'instaclone-95fd6.appspot.com',
    iosBundleId: 'com.example.instaGramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASGAJvqDsQ66FMOlTtJJi_SZlUHWEkgx8',
    appId: '1:413507224369:ios:c96f6ce125144f86032610',
    messagingSenderId: '413507224369',
    projectId: 'instaclone-95fd6',
    storageBucket: 'instaclone-95fd6.appspot.com',
    iosBundleId: 'com.example.instaGramClone.RunnerTests',
  );
}
